name: Keep Hugging Face Alive

on:
  schedule:
    - cron: '*/14 * * * *' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Memos URL 1
        run: curl -I https://memos.nachaos.xyz || true # 允许失败继续

      - name: Ping Memos URL 2
        run: curl -I https://memos.2410.space || true