name: Keep Hugging Face Alive

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Memos URL
        run: |
          curl -I https://memos.nachaos.xyz/
          curl -I 
https://memos.2410.space/